sudo: required

language: cpp

matrix:
  include:
    - env: COMPILER=g++-4.8
    # TODO(gordon) temporarily disabled (see travis build #24.2)
    #- env: COMPILER=g++-5
    - env: COMPILER=clang++-3.5

before_install:
  # Before doing anything else, let's be sure that the code at least has good style.
  - sudo pip install cpplint
  - .travis/run_lint.sh
  # Ok, now we can do all the rest of installing dependencies and whatnot
  - sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/trusty.list
  - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list.d/trusty.list
  - if [[ $COMPILER == g++-5       ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - sudo apt-get update -qq -y
  - if [[ $COMPILER == g++-4.8     ]]; then sudo apt-get install -q -y g++-4.8;     fi
  - if [[ $COMPILER == g++-5       ]]; then sudo apt-get install -q -y g++-5;       fi
  - if [[ $COMPILER == clang++-3.5 ]]; then sudo apt-get install -q -y clang++-3.5; fi
  - sudo apt-get install -qq -y --force-yes libprotobuf-dev
  - export CXX=$COMPILER
  # P4 dependencies
  - sudo apt-get install -q -y libjudy-dev
                               libgmp-dev
                               libpcap-dev
                               libboost-dev
                               libboost-test-dev
                               libboost-program-options-dev
                               libboost-system-dev
                               libboost-filesystem-dev
                               libboost-thread-dev
                               libevent-dev
  # Install SystemC
  - wget http://www.accellera.org/images/downloads/standards/systemc/systemc-2.3.1.tgz
  - tar -xzf systemc-2.3.1.tgz
  - cd systemc-2.3.1
  - ./configure --prefix=/usr --with-unix-layout
  - make
  - sudo make install
  - cd ..
  # Install nanomsg
  - wget http://download.nanomsg.org/nanomsg-0.5-beta.tar.gz
  - tar -xzf nanomsg-0.5-beta.tar.gz
  - cd nanomsg-0.5-beta
  - ./configure
  - make
  - sudo make install
  - cd ..
  # Install PFPSim core and PFP-P4
  - .travis/get-PFPSim.py "v1.3.0" "$CXX"
  - sudo dpkg -i pfpsim*.deb
  # Install pfpgen
  - .travis/get-pfpgen.py "v1.0.0"
  - sudo pip install pfpgen*.whl

install:
  - pfpgen npu.fad
  - cd npu/build
  - cmake ../src
  - make -j2

script:
  - cp -r ../build_static/* ./
  - ./runme.sh
